spring:
  config:
    activate:
      on-profile: local

  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.25.1.223:1521:qlimsdev
    username: qlims
    password: qlims_dev

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api
  port: 9223

logging:
  config: classpath:properties/logback-spring-local.xml
